### Importing Modules Required

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

### Importing CSV file in the name milk using Pandas


In [2]:
milk=pd.read_csv('milk.csv')

### Lets check size of the data

In [3]:
milk.shape

(1059, 8)

In [4]:
milk.size

8472

### Lets check for null values

In [5]:
milk.isnull().sum()

pH             0
Temperature    0
Taste          0
Odour          0
Fat            0
Turbidity      0
Colour         0
Grade          0
dtype: int64

In [6]:
### There Were No Null Values

### Lets Check Columns

In [7]:
milk.columns

Index(['pH', 'Temperature', 'Taste', 'Odour', 'Fat', 'Turbidity', 'Colour',
       'Grade'],
      dtype='object')

### Lets see data of five rows

In [8]:
milk.head()

pH  Temperature  Taste  Odour  Fat  Turbidity  Colour   Grade
0  6.6           35      1      0    1          0     254    high
1  6.6           36      0      1    0          1     253    high
2  8.5           70      1      1    1          1     246     low
3  9.5           34      1      1    0          1     255     low
4  6.6           37      0      0    0          0     255  medium

### Lets Check Information Regarding Each Column 

In [9]:
milk.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1059 entries, 0 to 1058
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   pH           1059 non-null   float64
 1   Temperature  1059 non-null   int64  
 2   Taste        1059 non-null   int64  
 3   Odour        1059 non-null   int64  
 4   Fat          1059 non-null   int64  
 5   Turbidity    1059 non-null   int64  
 6   Colour       1059 non-null   int64  
 7   Grade        1059 non-null   object 
dtypes: float64(1), int64(6), object(1)
memory usage: 66.3+ KB


### Lets Check Central Tendancy


In [10]:
milk.describe()

pH  Temperature        Taste        Odour          Fat  \
count  1059.000000  1059.000000  1059.000000  1059.000000  1059.000000   
mean      6.630123    44.226629     0.546742     0.432483     0.671388   
std       1.399679    10.098364     0.498046     0.495655     0.469930   
min       3.000000    34.000000     0.000000     0.000000     0.000000   
25%       6.500000    38.000000     0.000000     0.000000     0.000000   
50%       6.700000    41.000000     1.000000     0.000000     1.000000   
75%       6.800000    45.000000     1.000000     1.000000     1.000000   
max       9.500000    90.000000     1.000000     1.000000     1.000000   

         Turbidity       Colour  
count  1059.000000  1059.000000  
mean      0.491029   251.840415  
std       0.500156     4.307424  
min       0.000000   240.000000  
25%       0.000000   250.000000  
50%       0.000000   255.000000  
75%       1.000000   255.000000  
max       1.000000   255.000000

### Lets Check Unique Values of each column

In [11]:
milk['pH'].unique()

array([6.6, 8.5, 9.5, 5.5, 4.5, 8.1, 6.7, 5.6, 8.6, 7.4, 6.8, 6.5, 4.7,
       3. , 9. , 6.4])

In [12]:
milk['Temperature'].unique()

array([35, 36, 70, 34, 37, 45, 60, 66, 50, 55, 90, 38, 40, 43, 42, 41, 65],
      dtype=int64)

In [13]:
milk['Taste'].unique()

array([1, 0], dtype=int64)

In [14]:
milk['Odour'].unique()

array([0, 1], dtype=int64)

In [15]:
milk['Turbidity'].unique()

array([0, 1], dtype=int64)

In [17]:
milk['Colour'].unique()

array([254, 253, 246, 255, 250, 247, 245, 240, 248], dtype=int64)

In [18]:
milk['Fat'].unique()

array([1, 0], dtype=int64)

In [19]:
milk.corr()

pH  Temperature     Taste     Odour       Fat  Turbidity  \
pH           1.000000     0.244684 -0.064053 -0.081331 -0.093429   0.048384   
Temperature  0.244684     1.000000 -0.109792 -0.048870  0.024073   0.185106   
Taste       -0.064053    -0.109792  1.000000  0.017582  0.324149   0.055755   
Odour       -0.081331    -0.048870  0.017582  1.000000  0.314505   0.457935   
Fat         -0.093429     0.024073  0.324149  0.314505  1.000000   0.329264   
Turbidity    0.048384     0.185106  0.055755  0.457935  0.329264   1.000000   
Colour      -0.164565    -0.008511 -0.082654 -0.039361  0.114151   0.136436   

               Colour  
pH          -0.164565  
Temperature -0.008511  
Taste       -0.082654  
Odour       -0.039361  
Fat          0.114151  
Turbidity    0.136436  
Colour       1.000000

In [20]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
milk['Grade']=le.fit_transform(milk['Grade']).astype(int)

In [21]:
milk.head()

pH  Temperature  Taste  Odour  Fat  Turbidity  Colour  Grade
0  6.6           35      1      0    1          0     254      0
1  6.6           36      0      1    0          1     253      0
2  8.5           70      1      1    1          1     246      1
3  9.5           34      1      1    0          1     255      1
4  6.6           37      0      0    0          0     255      2